"""Add foreign key constraint to profiles.user_id

Revision ID: 2c1d8b8a28ab
Revises: 284156aaf71b
Create Date: 2025-02-26 11:15:44.772592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1d8b8a28ab'
down_revision: Union[str, None] = '284156aaf71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'profiles', ['author_id'], ['user_id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_public_profiles_username', table_name='profiles')
    op.drop_constraint('profiles_user_id_key', 'profiles', type_='unique')
    op.drop_column('profiles', 'username')

    # Add the foreign key constraint to profiles.user_id
    op.create_foreign_key(
        'fk_profiles_user_id_auth_users',
        'profiles', 'users',
        ['user_id'], ['id'],
        source_schema='public',
        referent_schema='auth',
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('profiles_user_id_key', 'profiles', ['user_id'])
    op.create_index('ix_public_profiles_username', 'profiles', ['username'], unique=True)
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'profiles', ['author_id'], ['user_id'])

    # Drop the foreign key constraint from profiles.user_id
    op.drop_constraint('fk_profiles_user_id_auth_users', 'profiles', schema='public', type_='foreignkey')
    # ### end Alembic commands ###
