"""Adding dummy table

Revision ID: 6daea96b83a6
Revises: 2c1d8b8a28ab
Create Date: 2025-02-26 11:49:20.411765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6daea96b83a6'
down_revision: Union[str, None] = '2c1d8b8a28ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'profiles', ['author_id'], ['user_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('fk_profiles_user_id_auth_users', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_profiles_user_id_auth_users', 'profiles', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'profiles', ['author_id'], ['user_id'])
    # ### end Alembic commands ###
