"""Added tables

Revision ID: 8182bba776ef
Revises: 7c722ffc2fbd
Create Date: 2025-02-24 22:34:10.300023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8182bba776ef'
down_revision: Union[str, None] = '7c722ffc2fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_profiles_full_name'), 'profiles', ['full_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_profiles_username'), 'profiles', ['username'], unique=True, schema='public')
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id'),
    sa.UniqueConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts', schema='public')
    op.drop_index(op.f('ix_public_profiles_username'), table_name='profiles', schema='public')
    op.drop_index(op.f('ix_public_profiles_full_name'), table_name='profiles', schema='public')
    op.drop_table('profiles', schema='public')
    # ### end Alembic commands ###
