"""removed name column

Revision ID: c5031ac0fb4d
Revises: 443091100fab
Create Date: 2025-02-27 08:27:07.415396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5031ac0fb4d'
down_revision: Union[str, None] = '443091100fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'profiles', ['author_id'], ['user_id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_public_profiles_full_name', table_name='profiles')
    op.drop_constraint('profiles_user_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='auth', ondelete='CASCADE')
    op.drop_column('profiles', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.create_index('ix_public_profiles_full_name', 'profiles', ['full_name'], unique=False)
    op.drop_constraint(None, 'posts', schema='public', type_='foreignkey')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'profiles', ['author_id'], ['user_id'])
    # ### end Alembic commands ###
