"""Add bio column to test table

Revision ID: 2cdc20e2803a
Revises: 9c9108efdefa
Create Date: 2025-02-24 12:55:06.666500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdc20e2803a'
down_revision: Union[str, None] = '9c9108efdefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_models', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_models', 'bio')
    # ### end Alembic commands ###
