"""Add roles column to profiles table

Revision ID: 4af4f78f8b0a
Revises: 2cdc20e2803a
Create Date: 2025-02-24 12:57:03.894251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af4f78f8b0a'
down_revision: Union[str, None] = '2cdc20e2803a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('role', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('roles', sa.Text(), nullable=True))
    op.drop_index('ix_profiles_full_name', table_name='profiles')
    op.drop_index('ix_profiles_username', table_name='profiles')
    op.create_index(op.f('ix_public_profiles_full_name'), 'profiles', ['full_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_profiles_username'), 'profiles', ['username'], unique=True, schema='public')
    op.drop_constraint('profiles_user_id_fkey', 'profiles', type_='foreignkey')
    op.drop_table_comment(
        'profiles',
        existing_comment='Stories Prorifle information for Blog Subscriber users',
        schema=None
    )
    op.add_column('test_models', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_models', 'bio')
    op.create_table_comment(
        'profiles',
        'Stories Prorifle information for Blog Subscriber users',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_public_profiles_username'), table_name='profiles', schema='public')
    op.drop_index(op.f('ix_public_profiles_full_name'), table_name='profiles', schema='public')
    op.create_index('ix_profiles_username', 'profiles', ['username'], unique=True)
    op.create_index('ix_profiles_full_name', 'profiles', ['full_name'], unique=False)
    op.drop_column('profiles', 'roles')
    op.drop_column('profiles', 'bio')
    op.drop_column('profiles', 'role')
    # ### end Alembic commands ###
