"""Updated profiles table

Revision ID: 760ab95d7100
Revises: 4af4f78f8b0a
Create Date: 2025-02-24 13:01:59.611552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760ab95d7100'
down_revision: Union[str, None] = '4af4f78f8b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'bio')
    op.drop_column('profiles', 'roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('roles', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
