"""Updated profiles table

Revision ID: ffc273641853
Revises: 760ab95d7100
Create Date: 2025-02-24 13:06:58.964352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc273641853'
down_revision: Union[str, None] = '760ab95d7100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_full_name'), 'user', ['full_name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_user_username'), 'user', ['username'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_username'), table_name='user', schema='public')
    op.drop_index(op.f('ix_public_user_full_name'), table_name='user', schema='public')
    op.drop_table('user', schema='public')
    # ### end Alembic commands ###
